title: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme

