title: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# With GitHub Pages Gem
theme: bulma-clean-theme

